language: node_js

node_js:
  - "stable"
  
cache:
  - npm
  - yarn

install:
  - yarn
  
script:
  - npm install
  - npm test 
  - npm run build
  
deploy:
  provider: surge
  skip_cleanup: true
  project : ./build/
  domain : bootcamp_owys_8.surge.sh

on:
    branch: master
  
  
  